DROP TABLE IF EXISTS test_table_schema;

CREATE TABLE test_table_schema (
    res GEOGRAPHY
);

INSERT INTO test_table_schema (res)
VALUES
  (ST_GEOGFROMTEXT('POINT EMPTY')),
  (ST_GEOGFROMTEXT('LINESTRING EMPTY')),
  (ST_GEOGFROMTEXT('POLYGON EMPTY')),
  (ST_GEOGFROMTEXT('MULTIPOINT EMPTY')),
  (ST_GEOGFROMTEXT('MULTILINESTRING EMPTY')),
  (ST_GEOGFROMTEXT('MULTIPOLYGON EMPTY')),
  (ST_GEOGFROMTEXT('GEOMETRYCOLLECTION EMPTY')),
  (ST_GEOGFROMTEXT('POINT(1 2)')),
  (ST_GEOGFROMTEXT('LINESTRING(1 2, 3 4)')),
  (ST_GEOGFROMTEXT('POLYGON((1 2, 3 4, 5 6, 1 2))')),
  (ST_GEOGFROMTEXT('MULTIPOINT(1 2, 3 4)')),
  (ST_GEOGFROMTEXT('MULTILINESTRING((1 2, 3 4), (5 6, 7 8))')),
  (ST_GEOGFROMTEXT('MULTIPOLYGON(((1 2, 3 4, 5 6, 1 2)), ((7 8, 9 10, 11 12, 7 8)))')),
  (ST_GEOGFROMTEXT('GEOMETRYCOLLECTION(POINT(1 2), LINESTRING(3 4, 5 6))'))
;
