# Copyright (c) 2025 Columnar Technologies, Inc.  All rights reserved.

[tags]
sql-type-name = "ARRAY"
caveats = ["BigQuery treats NULL arrays as empty arrays in result sets, even though you can differentiate between them during query execution.  See https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#array_nulls for more details."]
