DROP TABLE IF EXISTS test_geography;

CREATE TABLE test_geography (
    idx INTEGER,
    res GEOGRAPHY,
    res2 ARRAY<GEOGRAPHY>,
    res3 STRUCT<a GEOGRAPHY, b ARRAY<GEOGRAPHY>>
);

INSERT INTO test_geography (idx, res, res2, res3)
VALUES
  (0, ST_GEOGFROMTEXT('POINT EMPTY'), [ST_GEOGFROMTEXT('POINT EMPTY')], (ST_GEOGFROMTEXT('POINT EMPTY'), [ST_GEOGFROMTEXT('POINT EMPTY')])),
  (1, ST_GEOGFROMTEXT('LINESTRING EMPTY'), [ST_GEOGFROMTEXT('LINESTRING EMPTY')], (ST_GEOGFROMTEXT('LINESTRING EMPTY'), [ST_GEOGFROMTEXT('LINESTRING EMPTY')])),
  (2, ST_GEOGFROMTEXT('POLYGON EMPTY'), [ST_GEOGFROMTEXT('POLYGON EMPTY')], (ST_GEOGFROMTEXT('POLYGON EMPTY'), [ST_GEOGFROMTEXT('POLYGON EMPTY')])),
  (3, ST_GEOGFROMTEXT('MULTIPOINT EMPTY'), [ST_GEOGFROMTEXT('MULTIPOINT EMPTY')], (ST_GEOGFROMTEXT('MULTIPOINT EMPTY'), [ST_GEOGFROMTEXT('MULTIPOINT EMPTY')])),
  (4, ST_GEOGFROMTEXT('MULTILINESTRING EMPTY'), [ST_GEOGFROMTEXT('MULTILINESTRING EMPTY')], (ST_GEOGFROMTEXT('MULTILINESTRING EMPTY'), [ST_GEOGFROMTEXT('MULTILINESTRING EMPTY')])),
  (5, ST_GEOGFROMTEXT('MULTIPOLYGON EMPTY'), [ST_GEOGFROMTEXT('MULTIPOLYGON EMPTY')], (ST_GEOGFROMTEXT('MULTIPOLYGON EMPTY'), [ST_GEOGFROMTEXT('MULTIPOLYGON EMPTY')])),
  (6, ST_GEOGFROMTEXT('GEOMETRYCOLLECTION EMPTY'), [ST_GEOGFROMTEXT('GEOMETRYCOLLECTION EMPTY')], (ST_GEOGFROMTEXT('GEOMETRYCOLLECTION EMPTY'), [ST_GEOGFROMTEXT('GEOMETRYCOLLECTION EMPTY')])),
  (7, ST_GEOGFROMTEXT('POINT(1 2)'), [ST_GEOGFROMTEXT('POINT(1 2)')], (ST_GEOGFROMTEXT('POINT(1 2)'), [ST_GEOGFROMTEXT('POINT(1 2)')])),
  (8, ST_GEOGFROMTEXT('LINESTRING(1 2, 3 4)'), [ST_GEOGFROMTEXT('LINESTRING(1 2, 3 4)')], (ST_GEOGFROMTEXT('LINESTRING(1 2, 3 4)'), [ST_GEOGFROMTEXT('LINESTRING(1 2, 3 4)')])),
  (9, ST_GEOGFROMTEXT('POLYGON((1 2, 3 4, 5 6, 1 2))'), [ST_GEOGFROMTEXT('POLYGON((1 2, 3 4, 5 6, 1 2))')], (ST_GEOGFROMTEXT('POLYGON((1 2, 3 4, 5 6, 1 2))'), [ST_GEOGFROMTEXT('POLYGON((1 2, 3 4, 5 6, 1 2))')])),
  (10, ST_GEOGFROMTEXT('MULTIPOINT(1 2, 3 4)'), [ST_GEOGFROMTEXT('MULTIPOINT(1 2, 3 4)')], (ST_GEOGFROMTEXT('MULTIPOINT(1 2, 3 4)'), [ST_GEOGFROMTEXT('MULTIPOINT(1 2, 3 4)')])),
  (11, ST_GEOGFROMTEXT('MULTILINESTRING((1 2, 3 4), (5 6, 7 8))'), [ST_GEOGFROMTEXT('MULTILINESTRING((1 2, 3 4), (5 6, 7 8))')], (ST_GEOGFROMTEXT('MULTILINESTRING((1 2, 3 4), (5 6, 7 8))'), [ST_GEOGFROMTEXT('MULTILINESTRING((1 2, 3 4), (5 6, 7 8))')])),
  (12, ST_GEOGFROMTEXT('MULTIPOLYGON(((1 2, 3 4, 5 6, 1 2)), ((7 8, 9 10, 11 12, 7 8)))'), [ST_GEOGFROMTEXT('MULTIPOLYGON(((1 2, 3 4, 5 6, 1 2)), ((7 8, 9 10, 11 12, 7 8)))')], (ST_GEOGFROMTEXT('MULTIPOLYGON(((1 2, 3 4, 5 6, 1 2)), ((7 8, 9 10, 11 12, 7 8)))'), [ST_GEOGFROMTEXT('MULTIPOLYGON(((1 2, 3 4, 5 6, 1 2)), ((7 8, 9 10, 11 12, 7 8)))')])),
  (13, ST_GEOGFROMTEXT('GEOMETRYCOLLECTION(POINT(1 2), LINESTRING(3 4, 5 6))'), [ST_GEOGFROMTEXT('GEOMETRYCOLLECTION(POINT(1 2), LINESTRING(3 4, 5 6))')], (ST_GEOGFROMTEXT('GEOMETRYCOLLECTION(POINT(1 2), LINESTRING(3 4, 5 6))'), [ST_GEOGFROMTEXT('GEOMETRYCOLLECTION(POINT(1 2), LINESTRING(3 4, 5 6))')])),
  (14, NULL, NULL, (NULL, NULL))
;
