# Copyright (c) 2025 Columnar Technologies, Inc.  All rights reserved.
name = "ADBC Driver Foundry Driver for Google BigQuery"
publisher = "Columnar Technologies"
license = "Proprietary"

[ADBC]
version = "v1.1.0"
