# Copyright (c) 2025 Columnar Technologies, Inc.  All rights reserved.

[tags]
broken-vendor = "This is broken on Google's side, as BigQuery doesn't properly parse Parquet types. See https://github.com/googleapis/google-cloud-python/issues/6542."
sql-type-name = "DATETIME"
