# Copyright (c) 2025 Columnar Technologies, Inc.  All rights reserved.

name: Run Validation Suite

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    uses: adbc-drivers/dev/.github/workflows/validate.yaml@c8f3674fdc11a0cb611f18d7385baf630bda5473
    secrets:
      driverbase_private_key: ${{ secrets.DRIVERBASE_DEPLOY_KEY }}
      validation_private_key: ${{ secrets.VALIDATION_DEPLOY_KEY }}
    with:
      driver: bigquery
